In [3]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.9.0+cpu'

##Lists

In [4]:
my_list = [1, 2, 3 , 4, 5]

In [5]:
print(my_list[:5])

[1, 2, 3, 4, 5]


##Numpy Arrays

In [6]:
np1 = np.random.rand(3, 4) # just 3 rows of 4 columns randomly
np1

array([[0.97992092, 0.45791688, 0.33317112, 0.21213238],
       [0.38062096, 0.06143485, 0.7692304 , 0.33997737],
       [0.62572159, 0.23502957, 0.43086754, 0.50679705]])

##Tensors

In [7]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.5177, -0.5712,  0.7077, -0.6999],
        [-0.1781,  0.6534, -0.1346, -1.4945],
        [ 0.9146, -0.6440,  1.2166, -1.8952]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3 ,4)

In [10]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

##Tensor OPs

In [12]:
trch = torch.arange(10)
trch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Reshape and view

trch = trch.reshape(2, 5)

In [14]:
trch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
#grabbing slices
my_torch2 = torch.arange(10).reshape(2,-1)

In [19]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch2[:, 1:3]

tensor([[1, 2],
        [6, 7]])